version: '2.1'

services:
  localstack:
    privileged: true
    image: localstack/localstack:0.10.5
    ports:
      - '4567-4585:4567-4585'
      - '4590-4593:4590-4593'
      - '${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}'
    environment:
      - DEFAULT_REGION=us-east-1
      - SERVICES=${SERVICES- }
      - DEBUG="1"
      # - DEBUG=${DEBUG- }
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=docker-reuse
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "localstack-vol:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  localstack-vol: